{
 "title": "Tekton w/o logging",
 "tags": [
  "jenkins-x",
  "tekton"
 ],
 "time": { "from": "2022-06-09T17:39:13.557Z", "to": "2022-06-09T19:22:41.331Z" },
 "templating": {
  "list": [
   { "name": "controller", "query": "pipelinerun,taskrun" },
   {
    "name": "level",
    "query": "error, warning, info, debug, trace"
   },
   { "name": "search" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "query0", "query": { "query": "" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "PipelineRun Reconciliations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(tekton_pipelines_controller_reconcile_count{reconciler=\"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler\",cluster=\"$cluster\"}[60m]))"
    }
   ]
  },
  {
   "title": "TaskRun Reconciliations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (success) (rate(tekton_pipelines_controller_reconcile_count{reconciler=\"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler\", cluster=\"$cluster\"}[60m]))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\",status=\"true\",service=\"kube-state-metrics\",cluster=\"$cluster\"})",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_processes{container=\"POD\"})",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "Pipelines by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(tekton_pipelines_controller_pipelinerun_count{cluster=\"$cluster\"}[60m]))"
    }
   ]
  },
  {
   "title": "Running Pipelines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tekton_pipelines_controller_running_pipelineruns_count{cluster=\"$cluster\"})",
     "legendFormat": "running pipelines"
    }
   ]
  }
 ]
}